### ISSUE TITLE
data_manager.py: error: too few arguments

### ISSUE THREAD

**Issue by celinajose** [batxes/4c2vhic#10]
Hi!
I installed 4Cin with docker run and I have an error in generating a "volume" to access the data from the docker container.
I used the following command line:
> docker run -it -v /home/cjose/4C/MKN74_Prom/7_4Cin/ batxes/4cin_ubuntu data_manager.py

And obtained the following:
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
usage: data_manager.py [-h] [--fragments_in_each_bead FRAGMENTS_IN_EACH_BEAD]
                       [--uZ UZ] [--lZ LZ] [--max_distance MAX_DISTANCE]
                       data_dir
data_manager.py: error: too few arguments

Can you help solve this issue?

**Comment by batxes** [comment]
Hi!

you need to link the data folder in your computer with the data folder in the docker container. If your 4C data is in "/home/cjose/4C/MKN74_Prom/7_4Cin/" then you should run with:

`docker run -it -v /home/cjose/4C/MKN74_Prom/7_4Cin:/data batxes/4cin_ubuntu data_manager.py
`

I hope it is fixed. Don't hesitate to contact me if it is not working.

**Comment by celinasjose** [comment]
Hi!
Thank you for your fast response.
I still have the same issue.

**Comment by batxes** [comment]
oh right, so the error says 

`data_manager.py: error: too few arguments
`

so the script needs the data_dir argument.
u can fix it with: 

`docker run -it -v /home/cjose/4C/MKN74_Prom/7_4Cin:/data batxes/4cin_ubuntu data_manager.py /data/
`

The program should run, but you may encounter display issues for pyplot.
I recommend you run the data_manager.py locally, since you don't need many dependencies. Download the code, unzip it and then:

```
cd 4Cin-master/
python src/data_manager.py data/Shh_mouse/WT/ 
```

Then try with your own data.

I hope it works. Cheers!

**Comment by batxes** [comment]
I encourage you to run locally prepare_data.py script, generate the primers (https://github.com/batxes/4Cin#explained-usage) and then check the data with the data_manager.py.
Once you have the input data ready, you can run the program with docker.
I added new lines to https://github.com/batxes/4Cin#using-docker-to-execute-4cin. The line you need to execute has now two volumes. The second one comes handy so the new generated models are copied also in your computer while the docker image is running. 

cheers!

**Comment by celinajose** [comment]
Hi!
Thank you for your help.
So I followed your advice on prepare_data.py and data_manager.py scripts and everything works.

However, using the following command:
> docker run -it -v /home/cjose/4C/MKN74_Prom/7_4Cin:/data/ -v /home/cjose/4C/MKN74_Prom/7_4Cin:/home/cjose/4Cin-master/MKN74_Prom batxes/4cin_ubuntu 4Cin.py /data/ MKN74_Prom --cpu 10 --fragments_in_each_bead 20 --colormap magma_r

I obtained the following:
########## Pre-modeling ##########
Modeling with variable max_distance ranging 5000:15000
Traceback (most recent call last):
  File "/usr/bin/4Cin.py", line 1567, in <module>
    p.map(modeling,execute)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IndexError: list index out of range

Cheers!

**Comment by batxes** [comment]
Check the input date is correct. Prepare_data.py generates modified input data and adds the suffix "modified" to the files. You should only use the modified files (so the rest of the input data in the directory should be removed) and the primers.txt and primers_vhic.txt files should contain the files names with the suffix. Did you check that?

**Comment by celinajose** [comment]
yes, I've used the output data of prepare_data.py.

**Comment by batxes** [comment]
try this:
`docker run -it -v /home/cjose/4C/MKN74_Prom/7_4Cin:/data/ -v /home/cjose/4C/MKN74_Prom/7_4Cin_models:/opt/4Cin/MKN74_Prom batxes/4cin_ubuntu 4Cin.py /data/ MKN74_Prom --cpu 10 --fragments_in_each_bead 20 --colormap magma_r`
See that I modified the second volume. I would recommend to generate the models in another directory which is not the input dir.
Check if this works.
Does it work with the test data that it is available? If this works, we know that it has something to do with the input data.

**Comment by celinajose** [comment]
When I use the test data available it works:
> docker run -it -v /home/cjose/4Cin-master/data/Six_zebra/:/data/Six_zebra -v /home/cjose/Six_zebra:/home/cjose/4Cin/Six_zebra_models batxes/4cin_ubuntu 4Cin.py /data/Six_zebra/ Six_zebra_models --cpu 10 --fragments_in_each_bead 20 --colormap magma_r

However, when using my own data get the above mentioned error:
> docker run -it -v /home/cjose/4C/MKN74_Prom/7_4Cin:/data/ -v /home/cjose/4C/A10/7_4Cin:/home/cjose/4Cin/A10 batxes/4cin_ubuntu 4Cin.py /data/ A10 --cpu 10 --fragments_in_each_bead 20 --colormap magma_r

**Comment by batxes** [comment]
Can you check how your data looks comparing to the test data? They should have the same number of lines, no header and the input data regions should be the same. What I mean is that the restriction sites should be the same for all the data.

**Comment by celinajose** [comment]
Both files don't have header but have a different number of lines with different intervals:

File1:
chr1	610	739	0.0
chr1	739	743	0.0
chr1	743	780	0.0
chr1	780	801	0.0

File2:
chr1	609	610	0.0
chr1	610	611	0.0
chr1	611	612	0.0
chr1	612	739	0.0

Maybe prepare.data was not correctly performed.
Or maybe it is from how I generated the files. I generated a bedgraph from a bam file.

**Comment by batxes** [comment]
The problem is that you have a region:
chr1 610 739 0.0

and then in the other file this region is divided into:
chr1 610 611 0.0
chr1 611 612 0.0
chr1 612 739 0.0

You would have to normalize the regions: 
if there is a region with "start1" and "end1" in a file and there is the same "start1" in another file, it should have the same "end1" and not another "end". 
Maybe doing the average of those 3 regions in file 2 and converting into 
chr1 610 739 0.0

Because if you perform the data preparation this is the output:

~$ head a_modified 
chr1	609	610	0.0
chr1	610	739	0.0
chr1	611	612	0.0
chr1	612	739	0.0
chr1	739	743	0.0
chr1	743	780	0.0
chr1	780	801	0.0

~$ head b_modified 
chr1	609	610	0.0
chr1	610	611	0.0
chr1	611	612	0.0
chr1	612	739	0.0
chr1	739	743	0.0
chr1	743	780	0.0
chr1	780	801	0.0

You can see that there is a conflict with the regions starting in 610.
I don't have such tool to do the preprocessing, sorry.

**Comment by celinajose** [comment]
How did you generated the fragscount files?

**Comment by batxes** [comment]
I have not. I have always done a postprocessing of the data.
I was thinking that in your case you could create a binned file with
bedtools makewindows and maybe use intersect or map from bedtools suite.

Hau idatzi du celinajose (notifications@github.com) erabiltzaileak (2021
urt. 22, or. (13:40)):

**Comment by celinajose** [comment]
I will try that.
Thank you cery much for your help.

Cheers!

**Comment by celinajose** [comment]
Hi!
I solved the problem with the files, now I have the same start and end position and the same number of lines in each file.

However, when I run:
> docker run -it -v /home/cjose/4C/MKN74_Prom/7_4Cin:/data/ -v /home/cjose/4C/A10/7_4Cin:/home/cjose/4Cin/A10 batxes/4cin_ubuntu 4Cin.py /data/ A10 --cpu 10 --fragments_in_each_bead 20 --colormap magma_r

I get:
########## Pre-modeling ##########
Modeling with variable max_distance ranging 5000:15000

It doesn't finish and doesn't display any error.

When using test data everything works.

Cheers!

**Comment by batxes** [comment]
can u show me the head, the tail and how many lines one of your data files has?

**Comment by celinajose** [comment]
> head A10_R1.bedgraph_modified

chr10	609	610	0.0
chr10	610	611	0.0
chr10	611	612	0.0
chr10	612	739	0.0
chr10	739	743	0.0
chr10	743	749	0.0
chr10	749	750	0.0
chr10	750	780	0.0
chr10	780	801	0.0
chr10	801	802	0.0

> tail A10_R1.bedgraph_modified

chr11	248895907	248895927	0.0
chr11	248902219	248902227	0.0
chr11	248903223	248903265	0.0
chr11	248911453	248911484	0.0
chr11	248916189	248916209	0.0
chr11	248922280	248922300	0.0
chr11	248934816	248934828	0.0
chr11	248935757	248935777	0.0
chr11	248940002	248940012	0.0
chr11	248943407	248943427	0.0

> wc -l A10_R1.bedgraph_modified

673213 A10_R1.bedgraph_modified

**Comment by batxes** [comment]
Ok so I see couple of things. 
- First u are trying to model two chromosomes together, chr10 and chr11. The program is not able to do that. So you should first model a chromosome and then the other.
- Second, you should not model whole chromosomes. If your locus is, let's say, the HoxD locus, you should focus on that region +- 1 or 2 megas. So your files should be trimmed. For example, the HoxD locus is the position chr2:74,500,000-74,800,000 more or less. So you should model chr2:73,000,000-76,300,000 for example. This depends on your viewpoints/anchors and how much they reach or which is the longest contact they have. Another example is the Shh gene, which it has the ZRS enhancer at a distance of almost 1 mega. So you should model +-1 mega at least from Shh. All that I am saying here can be seen when u plot the 4Cseq profiles and you see which contacts you would trust and which u would not.

I hope it helps.
cheers!

**Comment by celinajose** [comment]
Hi!
This solved the issue.
However, when I use the following:
> docker run -it -v /home/cjose/4C/MKN74_Prom/7_4Cin:/data/ -v /home/cjose/4C/A10/7_4Cin:/home/cjose/4Cin/A10 batxes/4cin_ubuntu 4Cin.py /data/ A10 --cpu 5 --fragments_in_each_bead 20 --colormap magma_r

4Cin saves the files in the directory /opt/4Cin/A10/, that doesn't exist.

According to the read me, I should do as follows:
> docker run -it -v <path_where_my_4C_data_is>:/data/ -v <path_where_I_want_my_new_models>:/opt/4Cin/<Name_of_my_models> batxes/4cin_ubuntu 4Cin.py /data/ <Name_of_my_models> --cpu 10 --fragments_in_each_bead 20 --colormap magma_r

Should I change anything in the command used?

Thanks in advance.
Cheers!

**Comment by batxes** [comment]
Hi!

Yes, try this:

docker run -i -v /home/cjose/4C/MKN74_Prom/7_4Cin:/data/ -v /home/cjose/4C/A10/7_4Cin:/opt/4Cin/A10 batxes/4cin_ubuntu 4Cin.py /data/ A10 --cpu 5 --fragments_in_each_bead 20 --colormap magma_r

Both -v (volumes) are Your_computer:docker. 
So the models that will be generated in /opt/4Cin/A10 will be generated in /home/cjose/4C/A10/7_4Cin

I hope it works now

cheers!

**Comment by celinasjose** [comment]
Hi!
I followed your suggestion and everything was correct.
However, the code takes approximately 5 days to run.
Do you have any suggestions on how to improve this?

Cheers!

**Comment by batxes** [comment]
Depends on the resolution, the size of the fragments and the size of the locus. 

The papers says this:
```
Our tool can be parallelized, allowing an acceleration of the process. 50.000 models based
on a data set of5 4C-seq experiments and represented by 56 beads, can be generated in about halfan hour, on a computer with 20 cores and CPU’s of2.5GHz. A region with 14 different 4C-seq experiments and 211 beads can be modeled in 7 hours.
```

So if you are certain of the region you want to model, the only variable you cna modify is  "fragments_in_each_bead". If you set it  high, like 20, it represents 20 4C-seq fragments in a bead. So, imagine you have 500bps fragments, you would be representing 10Kb in each bead. So think on the resolution you would like to get the best out of the modeling.

cheers!

**Comment by celinasjose** [comment]
Thanks!

**Comment by celinajose** [comment]
Thanks!
